source 'https://rubygems.org'

gem 'rake', '>= 12.3.3'

# jekyll, which builds it all
# 3.0 includes sass processing
gem 'jekyll', '~> 3.9', '>= 3.9.0'

# Jekyll extensions
gem 'jekyll-redirect-from'
gem 'jekyll-paginate'

# JSON
gem 'json', '>= 2.3.0'

# For `rake watch`
gem 'rb-fsevent'

# For markdown header cleanup
gem 'sanitize', '~> 4.6', '>= 4.6.3'

# Markdown
gem 'redcarpet', '>= 3.5.1'

# Syntax highlighting
gem 'pygments.rb', '>= 1.0.0'

# Avoid having to poll for changes on Windows
gem 'wdm', '>= 0.1.0' if Gem.win_platform?